blueprint:
  name: Doorbell - Send camera snapshot to app
  description: 'When the doorbell is pushed, send a camera snapshot to your app.'

  domain: automation
  input:
    doorbell:
      name: Doorbell
      description: This is the doorbell sensor 
      selector:
        entity:
          domain: input_boolean
    camera:
      name: Camera
      description: The camera which creates the snapshot
      selector:
        entity:
          domain: camera
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications
      selector:
        device:
          integration: mobile_app
    notification_title:
      name: Notification title (Optional)
      description: 'Default: "Doorbell"'
      default: "Doorbell"

mode: single

trigger:
- platform: state
  entity_id: !input 'doorbell'
  from: "off"
  to: "on"

variables:
  camera: !input camera
  notify_device: !input notify_device
  notification_title: !input notification_title
  snapshot_create_file_path: "/config/www/tmp/snapshot_{{ states[camera].object_id }}.jpg"
  snapshot_access_file_path: "{{ snapshot_create_file_path | replace('/config/www','/local') }}"

action:
  - service: camera.snapshot
    entity_id: !input camera
    data:
      filename: "{{ snapshot_create_file_path }}"

  - device_id: !input notify_device
    domain: mobile_app
    type: notify
    title: "{{ notification_title }}"
    message: ""
    data: >
      {% set android_data = {"image": "%s"} | format(snapshot_access_file_path) %}
      {{ android_data }}
